 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sales", type: :request do

  describe "GET /index" do
    it "renders a successful response" do
      get sales_url
      expect(response).to be_successful
    end
  end

  describe "POST /import" do
    it "import a valid txt file" 
      # valid_file = fixture_file_upload('files/valid.txt', 'text/plain')
      # post import_sales_path file: valid_file
      # expect(response).to be_successful
      #

    it "not import a empty txt file" do
      post import_sales_path
      expect(response).to_not be_successful
    end

    it "not import invalid lines of text file"
  end

end
